modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
[[mods]]
modId="crittersandcompanions"
version="${file.jarVersion}"
displayName="Critters and Companions"
logoFile=""
authors=""
description='''

'''

[[dependencies.crittersandcompanions]]
    modId="geckolib3"
    mandatory=true
    versionRange="[3.0.27,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.crittersandcompanions]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.crittersandcompanions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
